package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
)

/* Automated syscalls generator for GoSTE */

func main() {
	// Find the unix package directory
	out, err := exec.Command("go", "list", "-f", "{{.Dir}}", "golang.org/x/sys/unix").Output()
	if err != nil {
		log.Fatalf("failed to locate golang.org/x/sys/unix: %v", err)
	}
	unixDir := strings.TrimSpace(string(out))

	// Identify the zsysnum file for the current platform
	fileName := fmt.Sprintf("zsysnum_%s_%s.go", runtime.GOOS, runtime.GOARCH)
	filePath := filepath.Join(unixDir, fileName)

	file, err := os.Open(filePath)
	if err != nil {
		log.Fatalf("failed to open syscall definition file %s: %v", filePath, err)
	}
	defer file.Close()

	// Parse the file for SYS_ constants
	// Example line: SYS_READ = 0
	re := regexp.MustCompile(`SYS_([A-Z0-9_]+)\s*=\s*([0-9]+)`)
	syscalls := make(map[string]string)

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		matches := re.FindStringSubmatch(line)
		if len(matches) == 3 {
			name := strings.ToLower(matches[1])
			id := matches[2]
			syscalls[id] = name
		}
	}

	if err := scanner.Err(); err != nil {
		log.Fatalf("error reading file: %v", err)
	}

	// Generate the Go source file
	outPath := "syscalls_generated.go"
	outFile, err := os.Create(outPath)
	if err != nil {
		log.Fatalf("failed to create output file: %v", err)
	}
	defer outFile.Close()

	fmt.Fprintln(outFile, "// Code generated by scripts/gen_syscalls.go; DO NOT EDIT.")
	fmt.Fprintln(outFile, "package engine")
	fmt.Fprintln(outFile, "")
	fmt.Fprintln(outFile, "var GeneratedSyscalls = map[int]string{")

	// We want to sort them numerically by ID for a cleaner and deterministic file
	var sortedIDs []int
	for idStr := range syscalls {
		var id int
		fmt.Sscanf(idStr, "%d", &id)
		sortedIDs = append(sortedIDs, id)
	}
	sort.Ints(sortedIDs)

	for _, id := range sortedIDs {
		fmt.Fprintf(outFile, "\t%d: \"%s\",\n", id, syscalls[fmt.Sprintf("%d", id)])
	}

	fmt.Fprintln(outFile, "}")
	fmt.Fprintln(outFile, "")
	fmt.Fprintln(outFile, "var GeneratedSyscallsByName = map[string]int{")

	for _, id := range sortedIDs {
		name := syscalls[fmt.Sprintf("%d", id)]
		fmt.Fprintf(outFile, "\t\"%s\": %d,\n", name, id)
	}

	fmt.Fprintln(outFile, "}")

	fmt.Printf("Generated %d syscalls in %s\n", len(syscalls), outPath)
}
